package models;
// Generated 12 feb. 2020 0:21:54 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BatoiLogicAddress generated by hbm2java
 */
public class BatoiLogicAddress  implements java.io.Serializable {


     private int id;
     private BatoiLogicCustomer batoiLogicCustomer;
     private BatoiLogicPostalCode batoiLogicPostalCode;
     private String name;
     private Integer createUid;
     private Date createDate;
     private Integer writeUid;
     private Date writeDate;
     private Set batoiLogicOrders = new HashSet(0);
     private Set batoiLogicBills = new HashSet(0);

    public BatoiLogicAddress() {
    }

	
    public BatoiLogicAddress(int id, BatoiLogicCustomer batoiLogicCustomer, BatoiLogicPostalCode batoiLogicPostalCode, String name) {
        this.id = id;
        this.batoiLogicCustomer = batoiLogicCustomer;
        this.batoiLogicPostalCode = batoiLogicPostalCode;
        this.name = name;
    }
    public BatoiLogicAddress(int id, BatoiLogicCustomer batoiLogicCustomer, BatoiLogicPostalCode batoiLogicPostalCode, String name, Integer createUid, Date createDate, Integer writeUid, Date writeDate, Set batoiLogicOrders, Set batoiLogicBills) {
       this.id = id;
       this.batoiLogicCustomer = batoiLogicCustomer;
       this.batoiLogicPostalCode = batoiLogicPostalCode;
       this.name = name;
       this.createUid = createUid;
       this.createDate = createDate;
       this.writeUid = writeUid;
       this.writeDate = writeDate;
       this.batoiLogicOrders = batoiLogicOrders;
       this.batoiLogicBills = batoiLogicBills;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public BatoiLogicCustomer getBatoiLogicCustomer() {
        return this.batoiLogicCustomer;
    }
    
    public void setBatoiLogicCustomer(BatoiLogicCustomer batoiLogicCustomer) {
        this.batoiLogicCustomer = batoiLogicCustomer;
    }
    public BatoiLogicPostalCode getBatoiLogicPostalCode() {
        return this.batoiLogicPostalCode;
    }
    
    public void setBatoiLogicPostalCode(BatoiLogicPostalCode batoiLogicPostalCode) {
        this.batoiLogicPostalCode = batoiLogicPostalCode;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getCreateUid() {
        return this.createUid;
    }
    
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Integer getWriteUid() {
        return this.writeUid;
    }
    
    public void setWriteUid(Integer writeUid) {
        this.writeUid = writeUid;
    }
    public Date getWriteDate() {
        return this.writeDate;
    }
    
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }
    public Set getBatoiLogicOrders() {
        return this.batoiLogicOrders;
    }
    
    public void setBatoiLogicOrders(Set batoiLogicOrders) {
        this.batoiLogicOrders = batoiLogicOrders;
    }
    public Set getBatoiLogicBills() {
        return this.batoiLogicBills;
    }
    
    public void setBatoiLogicBills(Set batoiLogicBills) {
        this.batoiLogicBills = batoiLogicBills;
    }

    @Override
    public String toString()
    {
        return "Spain%20"+this.batoiLogicPostalCode.getBatoiLogicCity().getProvince()
                +"%20"+this.batoiLogicPostalCode.getBatoiLogicCity().getName();
    }
}