package models;
// Generated 12 feb. 2020 0:21:54 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BatoiLogicOrder generated by hbm2java
 */
public class BatoiLogicOrder implements java.io.Serializable {

    private int id;
    private BatoiLogicAddress batoiLogicAddress;
    private BatoiLogicCustomer batoiLogicCustomer;
    private String name;
    private Date date;
    private String status;
    private String information;
    private Integer createUid;
    private Date createDate;
    private Integer writeUid;
    private Date writeDate;
    private Set batoiLogicDeliveryNotes = new HashSet(0);
    private Set batoiLogicOrderLines = new HashSet(0);
    private static final String[] MONTHS = {"January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"};

    public static final String PENDING = "0";
    public static final String READY = "1";
    public static final String OUT_FOR_DELIVERY = "2";
    public static final String DELIVERED = "3";
    public static final String NO_DELIVERED = "4";

    public BatoiLogicOrder() {
        batoiLogicOrderLines = new HashSet(0);
    }

    public BatoiLogicOrder(BatoiLogicAddress batoiLogicAddress, BatoiLogicCustomer batoiLogicCustomer, String name) {
        this.batoiLogicAddress = batoiLogicAddress;
        this.batoiLogicCustomer = batoiLogicCustomer;
        this.name = name;
    }

    public BatoiLogicOrder(BatoiLogicAddress batoiLogicAddress, BatoiLogicCustomer batoiLogicCustomer, String name, Date date, String status, String information, Integer createUid, Date createDate, Integer writeUid, Date writeDate, Set batoiLogicDeliveryNotes, Set batoiLogicOrderLines) {
        this.batoiLogicAddress = batoiLogicAddress;
        this.batoiLogicCustomer = batoiLogicCustomer;
        this.name = name;
        this.date = date;
        this.status = status;
        this.information = information;
        this.createUid = createUid;
        this.createDate = createDate;
        this.writeUid = writeUid;
        this.writeDate = writeDate;
        this.batoiLogicDeliveryNotes = batoiLogicDeliveryNotes;
        this.batoiLogicOrderLines = batoiLogicOrderLines;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public BatoiLogicAddress getBatoiLogicAddress() {
        return this.batoiLogicAddress;
    }

    public void setBatoiLogicAddress(BatoiLogicAddress batoiLogicAddress) {
        this.batoiLogicAddress = batoiLogicAddress;
    }

    // Watch out, this fails (created by hibernate)
    public String getOrderStatus() {
        String orderStatus = "";

        switch (Integer.parseInt(this.status)) {
            case 1:
                orderStatus = "READY";
                break;

            case 2:
                orderStatus = "OUT FOR DELIVERY";
                break;

            case 3:
                orderStatus = "DELIVERED";
                break;

            case 4:
                orderStatus = "NOT DELIVERED";
                break;

            case 0:
                orderStatus = "PENDING";
                break;
        }

        return orderStatus;
    }

    public BatoiLogicCustomer getBatoiLogicCustomer() {
        return this.batoiLogicCustomer;
    }

    public void setBatoiLogicCustomer(BatoiLogicCustomer batoiLogicCustomer) {
        this.batoiLogicCustomer = batoiLogicCustomer;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getInformation() {
        return this.information;
    }

    public void setInformation(String information) {
        this.information = information;
    }

    public Integer getCreateUid() {
        return this.createUid;
    }

    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public Integer getWriteUid() {
        return this.writeUid;
    }

    public void setWriteUid(Integer writeUid) {
        this.writeUid = writeUid;
    }

    public Date getWriteDate() {
        return this.writeDate;
    }

    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }

    public Set getBatoiLogicDeliveryNotes() {
        return this.batoiLogicDeliveryNotes;
    }

    public void setBatoiLogicDeliveryNotes(Set batoiLogicDeliveryNotes) {
        this.batoiLogicDeliveryNotes = batoiLogicDeliveryNotes;
    }

    public Set getBatoiLogicOrderLines() {
        return this.batoiLogicOrderLines;
    }

    public void setBatoiLogicOrderLines(Set batoiLogicOrderLines) {
        this.batoiLogicOrderLines = batoiLogicOrderLines;
    }

    @Override
    public String toString() {

        return this.status;
    }
}