package models;
// Generated 12 feb. 2020 0:21:54 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * BatoiLogicLocation generated by hbm2java
 */
public class BatoiLogicLocation  implements java.io.Serializable {


     private int id;
     private BatoiLogicDeliveryMan batoiLogicDeliveryMan;
     private double latitude;
     private double longitude;
     private Integer createUid;
     private Date createDate;
     private Integer writeUid;
     private Date writeDate;

    public BatoiLogicLocation() {
    }

	
    public BatoiLogicLocation(int id, BatoiLogicDeliveryMan batoiLogicDeliveryMan, double latitude, double longitude) {
        this.id = id;
        this.batoiLogicDeliveryMan = batoiLogicDeliveryMan;
        this.latitude = latitude;
        this.longitude = longitude;
    }
    public BatoiLogicLocation(int id, BatoiLogicDeliveryMan batoiLogicDeliveryMan, double latitude, double longitude, Integer createUid, Date createDate, Integer writeUid, Date writeDate) {
       this.id = id;
       this.batoiLogicDeliveryMan = batoiLogicDeliveryMan;
       this.latitude = latitude;
       this.longitude = longitude;
       this.createUid = createUid;
       this.createDate = createDate;
       this.writeUid = writeUid;
       this.writeDate = writeDate;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public BatoiLogicDeliveryMan getBatoiLogicDeliveryMan() {
        return this.batoiLogicDeliveryMan;
    }
    
    public void setBatoiLogicDeliveryMan(BatoiLogicDeliveryMan batoiLogicDeliveryMan) {
        this.batoiLogicDeliveryMan = batoiLogicDeliveryMan;
    }
    public double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }
    public double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }
    public Integer getCreateUid() {
        return this.createUid;
    }
    
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Integer getWriteUid() {
        return this.writeUid;
    }
    
    public void setWriteUid(Integer writeUid) {
        this.writeUid = writeUid;
    }
    public Date getWriteDate() {
        return this.writeDate;
    }
    
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }




}


