package models;
// Generated 12 feb. 2020 0:21:54 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * BatoiLogicBill generated by hbm2java
 */
public class BatoiLogicBill  implements java.io.Serializable {


     private int id;
     private BatoiLogicAddress batoiLogicAddress;
     private BatoiLogicDeliveryNote batoiLogicDeliveryNote;
     private Date date;
     private Integer createUid;
     private Date createDate;
     private Integer writeUid;
     private Date writeDate;

    public BatoiLogicBill() {
    }

	
    public BatoiLogicBill(BatoiLogicAddress batoiLogicAddress, BatoiLogicDeliveryNote batoiLogicDeliveryNote) {
        this.batoiLogicAddress = batoiLogicAddress;
        this.batoiLogicDeliveryNote = batoiLogicDeliveryNote;
    }
    public BatoiLogicBill(BatoiLogicAddress batoiLogicAddress, BatoiLogicDeliveryNote batoiLogicDeliveryNote, Date date, Date createDate, Date writeDate) {
       this.batoiLogicAddress = batoiLogicAddress;
       this.batoiLogicDeliveryNote = batoiLogicDeliveryNote;
       this.date = date;
       this.createDate = createDate;
       this.writeDate = writeDate;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public BatoiLogicAddress getBatoiLogicAddress() {
        return this.batoiLogicAddress;
    }
    
    public void setBatoiLogicAddress(BatoiLogicAddress batoiLogicAddress) {
        this.batoiLogicAddress = batoiLogicAddress;
    }
    public BatoiLogicDeliveryNote getBatoiLogicDeliveryNote() {
        return this.batoiLogicDeliveryNote;
    }
    
    public void setBatoiLogicDeliveryNote(BatoiLogicDeliveryNote batoiLogicDeliveryNote) {
        this.batoiLogicDeliveryNote = batoiLogicDeliveryNote;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Integer getCreateUid() {
        return this.createUid;
    }
    
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Integer getWriteUid() {
        return this.writeUid;
    }
    
    public void setWriteUid(Integer writeUid) {
        this.writeUid = writeUid;
    }
    public Date getWriteDate() {
        return this.writeDate;
    }
    
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }

    @Override
    public String toString() {
        return "BatoiLogicBill{" + "id=" + id + ", batoiLogicAddress=" + batoiLogicAddress 
                + ", batoiLogicDeliveryNote=" + batoiLogicDeliveryNote + ", date=" + date + ", createUid=" 
                + createUid + ", createDate=" + createDate + ", writeUid=" + writeUid 
                + ", writeDate=" + writeDate + '}';
    }   
}