package models;
// Generated 12 feb. 2020 0:21:54 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BatoiLogicDeliveryNote generated by hbm2java
 */
public class BatoiLogicDeliveryNote implements java.io.Serializable {

    private int id;
    private BatoiLogicOrder batoiLogicOrder;
    private BatoiLogicRoute batoiLogicRoute;
    private String notes;
    private Integer createUid;
    private Date createDate;
    private Integer writeUid;
    private Date writeDate;
    private Set batoiLogicBills = new HashSet(0);

    public BatoiLogicDeliveryNote() {
    }

    public BatoiLogicDeliveryNote(BatoiLogicOrder batoiLogicOrder) {
        this.batoiLogicOrder = batoiLogicOrder;
    }

    public BatoiLogicDeliveryNote(BatoiLogicOrder batoiLogicOrder, BatoiLogicRoute batoiLogicRoute, String notes, Integer createUid, Date createDate, Integer writeUid, Date writeDate, Set batoiLogicBills) {
        this.createDate = createDate;
        this.batoiLogicOrder = batoiLogicOrder;
        this.batoiLogicRoute = batoiLogicRoute;
        this.notes = notes;
        this.createUid = createUid;
        this.createDate = createDate;
        this.writeUid = writeUid;
        this.writeDate = writeDate;
        this.batoiLogicBills = batoiLogicBills;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public BatoiLogicOrder getBatoiLogicOrder() {
        return this.batoiLogicOrder;
    }

    public void setBatoiLogicOrder(BatoiLogicOrder batoiLogicOrder) {
        this.batoiLogicOrder = batoiLogicOrder;
    }

    public BatoiLogicRoute getBatoiLogicRoute() {
        return this.batoiLogicRoute;
    }

    public void setBatoiLogicRoute(BatoiLogicRoute batoiLogicRoute) {
        this.batoiLogicRoute = batoiLogicRoute;
    }

    public String getNotes() {
        return this.notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public Integer getCreateUid() {
        return this.createUid;
    }

    public String getShortedNotes()
    {
        StringBuilder result = new StringBuilder();

        if(notes!=null)
        {
            int cont = 0;
            for (int i = 0; i < notes.length(); i++) {
                cont++;
                if (cont > 40 && result.charAt(i - 1) == ' ') {
                    result.append(System.lineSeparator());
                    cont = 0;
                }

                result.append(notes.charAt(i));
            }
        }

        return result.toString();
    }

    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public Integer getWriteUid() {
        return this.writeUid;
    }

    public void setWriteUid(Integer writeUid) {
        this.writeUid = writeUid;
    }

    public Date getWriteDate() {
        return this.writeDate;
    }

    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }

    public Set getBatoiLogicBills() {
        return this.batoiLogicBills;
    }

    public void setBatoiLogicBills(Set batoiLogicBills) {
        this.batoiLogicBills = batoiLogicBills;
    }

    @Override
    public String toString() {
        return batoiLogicOrder + " " + batoiLogicRoute;
    }
}
