package models;
// Generated 12 feb. 2020 0:21:54 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * BatoiLogicInventory generated by hbm2java
 */
public class BatoiLogicInventory  implements java.io.Serializable {


     private int id;
     private BatoiLogicProduct batoiLogicProduct;
     private int stock;
     private String location;
     private Integer createUid;
     private Date createDate;
     private Integer writeUid;
     private Date writeDate;

    public BatoiLogicInventory() {
    }

	
    public BatoiLogicInventory(BatoiLogicProduct batoiLogicProduct, int stock, String location) {
        
        this.batoiLogicProduct = batoiLogicProduct;
        this.stock = stock;
        this.location = location;
    }
    public BatoiLogicInventory(int id, BatoiLogicProduct batoiLogicProduct, int stock, String location, Integer createUid, Date createDate, Integer writeUid, Date writeDate) {
       this.id = id;
       this.batoiLogicProduct = batoiLogicProduct;
       this.stock = stock;
       this.location = location;
       this.createUid = createUid;
       this.createDate = createDate;
       this.writeUid = writeUid;
       this.writeDate = writeDate;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public BatoiLogicProduct getBatoiLogicProduct() {
        return this.batoiLogicProduct;
    }
    
    public void setBatoiLogicProduct(BatoiLogicProduct batoiLogicProduct) {
        this.batoiLogicProduct = batoiLogicProduct;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public Integer getCreateUid() {
        return this.createUid;
    }
    
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Integer getWriteUid() {
        return this.writeUid;
    }
    
    public void setWriteUid(Integer writeUid) {
        this.writeUid = writeUid;
    }
    public Date getWriteDate() {
        return this.writeDate;
    }
    
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }

    @Override
    public String toString() {
        return "BatoiLogicInventory{" + "id=" + id + ", batoiLogicProduct=" + batoiLogicProduct 
                + ", stock=" + stock + ", location=" + location + ", createUid=" 
                + createUid + ", createDate=" + createDate + ", writeUid=" + writeUid 
                + ", writeDate=" + writeDate + '}';
    } 
}