package models;
// Generated 12 feb. 2020 0:21:54 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BatoiLogicCity generated by hbm2java
 */
public class BatoiLogicCity  implements java.io.Serializable {


     private int id;
     private String name;
     private String province;
     private Integer createUid;
     private Date createDate;
     private Integer writeUid;
     private Date writeDate;
     private Set batoiLogicPostalCodes = new HashSet(0);

    public BatoiLogicCity() {
    }

	
    public BatoiLogicCity(int id, String name, String province) {
        this.id = id;
        this.name = name;
        this.province = province;
    }
    public BatoiLogicCity(int id, String name, String province, Integer createUid, Date createDate, Integer writeUid, Date writeDate, Set batoiLogicPostalCodes) {
       this.id = id;
       this.name = name;
       this.province = province;
       this.createUid = createUid;
       this.createDate = createDate;
       this.writeUid = writeUid;
       this.writeDate = writeDate;
       this.batoiLogicPostalCodes = batoiLogicPostalCodes;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
    public Integer getCreateUid() {
        return this.createUid;
    }
    
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Integer getWriteUid() {
        return this.writeUid;
    }
    
    public void setWriteUid(Integer writeUid) {
        this.writeUid = writeUid;
    }
    public Date getWriteDate() {
        return this.writeDate;
    }
    
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }
    public Set getBatoiLogicPostalCodes() {
        return this.batoiLogicPostalCodes;
    }
    
    public void setBatoiLogicPostalCodes(Set batoiLogicPostalCodes) {
        this.batoiLogicPostalCodes = batoiLogicPostalCodes;
    }

    @Override
    public String toString() {
        return "BatoiLogicCity{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", province='" + province + '\'' +
                '}';
    }
}