package models;

// Generated 12 feb. 2020 0:21:54 by Hibernate Tools 4.3.1
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BatoiLogicLorry generated by hbm2java
 */
public class BatoiLogicLorry  implements java.io.Serializable {


     private int id;
     private String name;
     private String licensePlate;
     private int capacity;
     private Integer currentLoad;
     private Integer createUid;
     private Date createDate;
     private Integer writeUid;
     private Date writeDate;
     private Set batoiLogicDeliveryMans = new HashSet(0);

    public BatoiLogicLorry() {
    }

	
    public BatoiLogicLorry(int id, String name, String licensePlate, int capacity) {
        this.id = id;
        this.name = name;
        this.licensePlate = licensePlate;
        this.capacity = capacity;
    }
    public BatoiLogicLorry(int id, String name, String licensePlate, int capacity, Integer currentLoad, Integer createUid, Date createDate, Integer writeUid, Date writeDate, Set batoiLogicDeliveryMans) {
       this.id = id;
       this.name = name;
       this.licensePlate = licensePlate;
       this.capacity = capacity;
       this.currentLoad = currentLoad;
       this.createUid = createUid;
       this.createDate = createDate;
       this.writeUid = writeUid;
       this.writeDate = writeDate;
       this.batoiLogicDeliveryMans = batoiLogicDeliveryMans;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLicensePlate() {
        return this.licensePlate;
    }
    
    public void setLicensePlate(String licensePlate) {
        this.licensePlate = licensePlate;
    }
    public int getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(int capacity) {
        this.capacity = capacity;
    }
    public Integer getCurrentLoad() {
        return this.currentLoad;
    }
    
    public void setCurrentLoad(Integer currentLoad) {
        this.currentLoad = currentLoad;
    }
    public Integer getCreateUid() {
        return this.createUid;
    }
    
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Integer getWriteUid() {
        return this.writeUid;
    }
    
    public void setWriteUid(Integer writeUid) {
        this.writeUid = writeUid;
    }
    public Date getWriteDate() {
        return this.writeDate;
    }
    
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }
    public Set getBatoiLogicDeliveryMans() {
        return this.batoiLogicDeliveryMans;
    }
    
    public void setBatoiLogicDeliveryMans(Set batoiLogicDeliveryMans) {
        this.batoiLogicDeliveryMans = batoiLogicDeliveryMans;
    }
    
    public boolean isFull() {
        return this.currentLoad == this.capacity;
    }

    @Override
    public String toString() {
        return "BatoiLogicLorry{" + "id=" + id + ", name=" + name + ", licensePlate=" + licensePlate + ", capacity=" 
                + capacity + ", currentLoad=" + currentLoad + ", createUid=" + createUid + ", createDate=" 
                + createDate + ", writeUid=" + writeUid + ", writeDate=" + writeDate + ", batoiLogicDeliveryMans=" 
                + batoiLogicDeliveryMans + '}';
    }
}