package models;
// Generated 12 feb. 2020 0:21:54 by Hibernate Tools 4.3.1

import java.io.BufferedOutputStream;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.math.BigDecimal;
import java.net.MalformedURLException;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javafx.scene.image.Image;
import javax.xml.bind.DatatypeConverter;

import odooAPI.SimpleProductDAO;
import org.apache.commons.codec.binary.Base64;
import org.apache.xmlrpc.XmlRpcException;

/**
 * BatoiLogicProduct generated by hbm2java
 */
public class BatoiLogicProduct implements java.io.Serializable {

    private int id;
    private String name;
    private BigDecimal price;
    private BigDecimal kg;
    private String description;
    private Integer createUid;
    private String image;
    private Date createDate;
    private Integer writeUid;
    private Date writeDate;
    private Image realImage;
    private Set batoiLogicProductBatoiLogicProviderRels = new HashSet(0);
    private Set batoiLogicInventories = new HashSet(0);
    private Set batoiLogicOrderLines = new HashSet(0);
    private Set batoiLogicSupplierOrders = new HashSet(0);

    public BatoiLogicProduct() {
    }

    public BatoiLogicProduct(int id, String name, BigDecimal price) {
        this.id = id;
        this.name = name;
        this.price = price;
    }

    public BatoiLogicProduct(int id, String name, BigDecimal price, BigDecimal kg, String description, Integer createUid, Date createDate, Integer writeUid, Date writeDate, Set batoiLogicProductBatoiLogicProviderRels, Set batoiLogicInventories, Set batoiLogicOrderLines, Set batoiLogicSupplierOrders) {
        this.id = id;
        this.name = name;
        this.price = price;
        this.kg = kg;
        this.description = description;
        this.createUid = createUid;
        this.createDate = createDate;
        this.writeUid = writeUid;
        this.writeDate = writeDate;
        this.batoiLogicProductBatoiLogicProviderRels = batoiLogicProductBatoiLogicProviderRels;
        this.batoiLogicInventories = batoiLogicInventories;
        this.batoiLogicOrderLines = batoiLogicOrderLines;
        this.batoiLogicSupplierOrders = batoiLogicSupplierOrders;
    }

    public Image getRealImage() {
        return realImage;
    }

    public void setRealImage(Image realImage) {
        this.realImage = realImage;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) throws Exception {
        realImage = new SimpleProductDAO().findImageByPk(id);
    }

    public void setName(String name) {
        this.name = name;
    }

    public BigDecimal getPrice() {
        return this.price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public BigDecimal getKg() {
        return this.kg;
    }

    public void setKg(BigDecimal kg) {
        this.kg = kg;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getCreateUid() {
        return this.createUid;
    }

    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }

    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public Integer getWriteUid() {
        return this.writeUid;
    }

    public void setWriteUid(Integer writeUid) {
        this.writeUid = writeUid;
    }

    public Date getWriteDate() {
        return this.writeDate;
    }

    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }

    public Set getBatoiLogicProductBatoiLogicProviderRels() {
        return this.batoiLogicProductBatoiLogicProviderRels;
    }

    public void setBatoiLogicProductBatoiLogicProviderRels(Set batoiLogicProductBatoiLogicProviderRels) {
        this.batoiLogicProductBatoiLogicProviderRels = batoiLogicProductBatoiLogicProviderRels;
    }

    public Set getBatoiLogicInventories() {
        return this.batoiLogicInventories;
    }

    public void setBatoiLogicInventories(Set batoiLogicInventories) {
        this.batoiLogicInventories = batoiLogicInventories;
    }

    public Set getBatoiLogicOrderLines() {
        return this.batoiLogicOrderLines;
    }

    public void setBatoiLogicOrderLines(Set batoiLogicOrderLines) {
        this.batoiLogicOrderLines = batoiLogicOrderLines;
    }

    public Set getBatoiLogicSupplierOrders() {
        return this.batoiLogicSupplierOrders;
    }

    public void setBatoiLogicSupplierOrders(Set batoiLogicSupplierOrders) {
        this.batoiLogicSupplierOrders = batoiLogicSupplierOrders;
    }

    public String toString(){
        return name;
    }
}