package models;
// Generated 12 feb. 2020 0:21:54 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BatoiLogicProvider generated by hbm2java
 */
public class BatoiLogicProvider  implements java.io.Serializable {


     private int id;
     private String name;
     private String cif;
     private String email;
     private Integer telephone;
     private Integer createUid;
     private Date createDate;
     private Integer writeUid;
     private Date writeDate;
     private Set batoiLogicProviderBatoiLogicSupplierOrderRels = new HashSet(0);
     private Set batoiLogicProductBatoiLogicProviderRels = new HashSet(0);
     private Set batoiLogicSupplierOrders = new HashSet(0);

    public BatoiLogicProvider() {
    }

	
    public BatoiLogicProvider(int id, String name, String cif) {
        this.id = id;
        this.name = name;
        this.cif = cif;
    }
    public BatoiLogicProvider(int id, String name, String cif, String email, Integer telephone, Integer createUid, Date createDate, Integer writeUid, Date writeDate, Set batoiLogicProviderBatoiLogicSupplierOrderRels, Set batoiLogicProductBatoiLogicProviderRels, Set batoiLogicSupplierOrders) {
       this.id = id;
       this.name = name;
       this.cif = cif;
       this.email = email;
       this.telephone = telephone;
       this.createUid = createUid;
       this.createDate = createDate;
       this.writeUid = writeUid;
       this.writeDate = writeDate;
       this.batoiLogicProviderBatoiLogicSupplierOrderRels = batoiLogicProviderBatoiLogicSupplierOrderRels;
       this.batoiLogicProductBatoiLogicProviderRels = batoiLogicProductBatoiLogicProviderRels;
       this.batoiLogicSupplierOrders = batoiLogicSupplierOrders;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCif() {
        return this.cif;
    }
    
    public void setCif(String cif) {
        this.cif = cif;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(Integer telephone) {
        this.telephone = telephone;
    }
    public Integer getCreateUid() {
        return this.createUid;
    }
    
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Integer getWriteUid() {
        return this.writeUid;
    }
    
    public void setWriteUid(Integer writeUid) {
        this.writeUid = writeUid;
    }
    public Date getWriteDate() {
        return this.writeDate;
    }
    
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }
    public Set getBatoiLogicProviderBatoiLogicSupplierOrderRels() {
        return this.batoiLogicProviderBatoiLogicSupplierOrderRels;
    }
    
    public void setBatoiLogicProviderBatoiLogicSupplierOrderRels(Set batoiLogicProviderBatoiLogicSupplierOrderRels) {
        this.batoiLogicProviderBatoiLogicSupplierOrderRels = batoiLogicProviderBatoiLogicSupplierOrderRels;
    }
    public Set getBatoiLogicProductBatoiLogicProviderRels() {
        return this.batoiLogicProductBatoiLogicProviderRels;
    }
    
    public void setBatoiLogicProductBatoiLogicProviderRels(Set batoiLogicProductBatoiLogicProviderRels) {
        this.batoiLogicProductBatoiLogicProviderRels = batoiLogicProductBatoiLogicProviderRels;
    }
    public Set getBatoiLogicSupplierOrders() {
        return this.batoiLogicSupplierOrders;
    }
    
    public void setBatoiLogicSupplierOrders(Set batoiLogicSupplierOrders) {
        this.batoiLogicSupplierOrders = batoiLogicSupplierOrders;
    }

    @Override
    public String toString() {
        return name;
    }
}


