package models;
// Generated 12 feb. 2020 0:21:54 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * BatoiLogicRoute generated by hbm2java
 */
public class BatoiLogicRoute  implements java.io.Serializable {

     private int id;
     private BatoiLogicDeliveryMan batoiLogicDeliveryMan;
     private Integer createUid;
     private Date createDate;
     private Integer writeUid;
     private Date writeDate;
     private List<BatoiLogicDeliveryNote> note;
     private Set batoiLogicDeliveryNotes = new HashSet(0);

    public BatoiLogicRoute() {
    }

    public List<BatoiLogicDeliveryNote> getNote() {
        return note;
    }

    public void setNote(List<BatoiLogicDeliveryNote> note) {
        this.note = note;
    }

    public BatoiLogicRoute(BatoiLogicDeliveryMan batoiLogicDeliveryMan) {
        this.batoiLogicDeliveryMan = batoiLogicDeliveryMan;
    }
    public BatoiLogicRoute(BatoiLogicDeliveryMan batoiLogicDeliveryMan, Integer createUid, Date createDate, Integer writeUid, Date writeDate, Set batoiLogicDeliveryNotes) {
       this.batoiLogicDeliveryMan = batoiLogicDeliveryMan;
       this.createUid = createUid;
       this.createDate = createDate;
       this.writeUid = writeUid;
       this.writeDate = writeDate;
       this.batoiLogicDeliveryNotes = batoiLogicDeliveryNotes;
    }

    public BatoiLogicRoute(BatoiLogicDeliveryMan dman, List<BatoiLogicDeliveryNote> note)
    {
        this.batoiLogicDeliveryMan = dman;
        this.note = note;
    }

    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public BatoiLogicDeliveryMan getBatoiLogicDeliveryMan() {
        return this.batoiLogicDeliveryMan;
    }
    
    public void setBatoiLogicDeliveryMan(BatoiLogicDeliveryMan batoiLogicDeliveryMan) {
        this.batoiLogicDeliveryMan = batoiLogicDeliveryMan;
    }
    public Integer getCreateUid() {
        return this.createUid;
    }
    
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Integer getWriteUid() {
        return this.writeUid;
    }
    
    public void setWriteUid(Integer writeUid) {
        this.writeUid = writeUid;
    }
    public Date getWriteDate() {
        return this.writeDate;
    }
    
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }
    public Set getBatoiLogicDeliveryNotes() {
        return this.batoiLogicDeliveryNotes;
    }
    
    public void setBatoiLogicDeliveryNotes(Set batoiLogicDeliveryNotes) {
        this.batoiLogicDeliveryNotes = batoiLogicDeliveryNotes;
    }
}