package models;
// Generated 5 feb. 2020 1:10:54 by Hibernate Tools 4.3.1



/**
 * BatoiLogicProductBatoiLogicProviderRel generated by hbm2java
 */
public class BatoiLogicProductBatoiLogicProviderRel  implements java.io.Serializable {


     private BatoiLogicProductBatoiLogicProviderRelId id;
     private BatoiLogicProduct batoiLogicProduct;
     private BatoiLogicProvider batoiLogicProvider;

    public BatoiLogicProductBatoiLogicProviderRel() {
    }

    public BatoiLogicProductBatoiLogicProviderRel(BatoiLogicProductBatoiLogicProviderRelId id, BatoiLogicProduct batoiLogicProduct, BatoiLogicProvider batoiLogicProvider) {
       this.id = id;
       this.batoiLogicProduct = batoiLogicProduct;
       this.batoiLogicProvider = batoiLogicProvider;
    }
   
    public BatoiLogicProductBatoiLogicProviderRelId getId() {
        return this.id;
    }
    
    public void setId(BatoiLogicProductBatoiLogicProviderRelId id) {
        this.id = id;
    }
    public BatoiLogicProduct getBatoiLogicProduct() {
        return this.batoiLogicProduct;
    }
    
    public void setBatoiLogicProduct(BatoiLogicProduct batoiLogicProduct) {
        this.batoiLogicProduct = batoiLogicProduct;
    }
    public BatoiLogicProvider getBatoiLogicProvider() {
        return this.batoiLogicProvider;
    }
    
    public void setBatoiLogicProvider(BatoiLogicProvider batoiLogicProvider) {
        this.batoiLogicProvider = batoiLogicProvider;
    }




}


