package models;
// Generated 5 feb. 2020 1:10:54 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BatoiLogicPostalCode generated by hbm2java
 */
public class BatoiLogicPostalCode  implements java.io.Serializable {


     private int id;
     private BatoiLogicCity batoiLogicCity;
     private int name;
     private Integer createUid;
     private Date createDate;
     private Integer writeUid;
     private Date writeDate;
     private Set batoiLogicAddresses = new HashSet(0);

    public BatoiLogicPostalCode() {
    }

	
    public BatoiLogicPostalCode(int id, BatoiLogicCity batoiLogicCity, int name) {
        this.id = id;
        this.batoiLogicCity = batoiLogicCity;
        this.name = name;
    }
    public BatoiLogicPostalCode(int id, BatoiLogicCity batoiLogicCity, int name, Integer createUid, Date createDate, Integer writeUid, Date writeDate, Set batoiLogicAddresses) {
       this.id = id;
       this.batoiLogicCity = batoiLogicCity;
       this.name = name;
       this.createUid = createUid;
       this.createDate = createDate;
       this.writeUid = writeUid;
       this.writeDate = writeDate;
       this.batoiLogicAddresses = batoiLogicAddresses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public BatoiLogicCity getBatoiLogicCity() {
        return this.batoiLogicCity;
    }
    
    public void setBatoiLogicCity(BatoiLogicCity batoiLogicCity) {
        this.batoiLogicCity = batoiLogicCity;
    }
    public int getName() {
        return this.name;
    }
    
    public void setName(int name) {
        this.name = name;
    }
    public Integer getCreateUid() {
        return this.createUid;
    }
    
    public void setCreateUid(Integer createUid) {
        this.createUid = createUid;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Integer getWriteUid() {
        return this.writeUid;
    }
    
    public void setWriteUid(Integer writeUid) {
        this.writeUid = writeUid;
    }
    public Date getWriteDate() {
        return this.writeDate;
    }
    
    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }
    public Set getBatoiLogicAddresses() {
        return this.batoiLogicAddresses;
    }
    
    public void setBatoiLogicAddresses(Set batoiLogicAddresses) {
        this.batoiLogicAddresses = batoiLogicAddresses;
    }

    @Override
    public String toString() {
        return String.valueOf(this.name);
    }    

}


