package models;
// Generated 5 feb. 2020 1:10:54 by Hibernate Tools 4.3.1

/**
 * BatoiLogicProviderBatoiLogicSupplierOrderRel generated by hbm2java
 */
public class BatoiLogicProviderBatoiLogicSupplierOrderRel  implements java.io.Serializable {


     private BatoiLogicProviderBatoiLogicSupplierOrderRelId id;
     private BatoiLogicProvider batoiLogicProvider;
     private BatoiLogicSupplierOrder batoiLogicSupplierOrder;

    public BatoiLogicProviderBatoiLogicSupplierOrderRel() {
    }

    public BatoiLogicProviderBatoiLogicSupplierOrderRel(BatoiLogicProviderBatoiLogicSupplierOrderRelId id, BatoiLogicProvider batoiLogicProvider, BatoiLogicSupplierOrder batoiLogicSupplierOrder) {
       this.id = id;
       this.batoiLogicProvider = batoiLogicProvider;
       this.batoiLogicSupplierOrder = batoiLogicSupplierOrder;
    }
   
    public BatoiLogicProviderBatoiLogicSupplierOrderRelId getId() {
        return this.id;
    }
    
    public void setId(BatoiLogicProviderBatoiLogicSupplierOrderRelId id) {
        this.id = id;
    }
    public BatoiLogicProvider getBatoiLogicProvider() {
        return this.batoiLogicProvider;
    }
    
    public void setBatoiLogicProvider(BatoiLogicProvider batoiLogicProvider) {
        this.batoiLogicProvider = batoiLogicProvider;
    }
    public BatoiLogicSupplierOrder getBatoiLogicSupplierOrder() {
        return this.batoiLogicSupplierOrder;
    }
    
    public void setBatoiLogicSupplierOrder(BatoiLogicSupplierOrder batoiLogicSupplierOrder) {
        this.batoiLogicSupplierOrder = batoiLogicSupplierOrder;
    }




}


