package models;
// Generated 5 feb. 2020 1:10:54 by Hibernate Tools 4.3.1

/**
 * BatoiLogicProductBatoiLogicProviderRelId generated by hbm2java
 */
public class BatoiLogicProductBatoiLogicProviderRelId  implements java.io.Serializable {


     private int batoiLogicProductId;
     private int batoiLogicProviderId;

    public BatoiLogicProductBatoiLogicProviderRelId() {
    }

    public BatoiLogicProductBatoiLogicProviderRelId(int batoiLogicProductId, int batoiLogicProviderId) {
       this.batoiLogicProductId = batoiLogicProductId;
       this.batoiLogicProviderId = batoiLogicProviderId;
    }
   
    public int getBatoiLogicProductId() {
        return this.batoiLogicProductId;
    }
    
    public void setBatoiLogicProductId(int batoiLogicProductId) {
        this.batoiLogicProductId = batoiLogicProductId;
    }
    public int getBatoiLogicProviderId() {
        return this.batoiLogicProviderId;
    }
    
    public void setBatoiLogicProviderId(int batoiLogicProviderId) {
        this.batoiLogicProviderId = batoiLogicProviderId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BatoiLogicProductBatoiLogicProviderRelId) ) return false;
		 BatoiLogicProductBatoiLogicProviderRelId castOther = ( BatoiLogicProductBatoiLogicProviderRelId ) other; 
         
		 return (this.getBatoiLogicProductId()==castOther.getBatoiLogicProductId())
 && (this.getBatoiLogicProviderId()==castOther.getBatoiLogicProviderId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getBatoiLogicProductId();
         result = 37 * result + this.getBatoiLogicProviderId();
         return result;
   }   
}