package models;
// Generated 5 feb. 2020 1:10:54 by Hibernate Tools 4.3.1

/**
 * BatoiLogicOrderLine generated by hbm2java
 */
public class BatoiLogicOrderLine  implements java.io.Serializable
{
     private int id;
     private BatoiLogicOrder batoiLogicOrder;
     private BatoiLogicProduct batoiLogicProduct;
     private int quantity;

    public BatoiLogicOrderLine()
    {
    }
	
    public BatoiLogicOrderLine(BatoiLogicOrder batoiLogicOrder, BatoiLogicProduct batoiLogicProduct, int quantity)
    {
//        this.id = id;
        this.batoiLogicOrder = batoiLogicOrder;
        this.batoiLogicProduct = batoiLogicProduct;
        this.quantity = quantity;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public BatoiLogicOrder getBatoiLogicOrder() {
        return this.batoiLogicOrder;
    }
    
    public void setBatoiLogicOrder(BatoiLogicOrder batoiLogicOrder) {
        this.batoiLogicOrder = batoiLogicOrder;
    }
    public BatoiLogicProduct getBatoiLogicProduct() {
        return this.batoiLogicProduct;
    }
    
    public void setBatoiLogicProduct(BatoiLogicProduct batoiLogicProduct) {
        this.batoiLogicProduct = batoiLogicProduct;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    @Override
    public String toString() {
        return "BatoiLogicOrderLine{" +
                "id=" + id +
                ", batoiLogicOrder=" + batoiLogicOrder.getName() +
                ", batoiLogicProduct=" + batoiLogicProduct.getName() +
                ", quantity=" + quantity +
                '}';
    }
}