package models;
// Generated 5 feb. 2020 1:10:54 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * BatoiLogicSupplierOrder generated by hbm2java
 */
public class BatoiLogicSupplierOrder  implements java.io.Serializable
{
     private int id;
     private BatoiLogicProduct batoiLogicProduct;
     private BatoiLogicProvider batoiLogicProvider;
     private int quantity;
     private Date requestDate;

    public BatoiLogicSupplierOrder() {
    }

    public BatoiLogicSupplierOrder(int id, BatoiLogicProduct batoiLogicProduct, BatoiLogicProvider batoiLogicProvider, int quantity, Date requestDate) {
        this.id = id;
        this.batoiLogicProduct = batoiLogicProduct;
        this.batoiLogicProvider = batoiLogicProvider;
        this.quantity = quantity;
        this.requestDate = requestDate;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public BatoiLogicProduct getBatoiLogicProduct() {
        return this.batoiLogicProduct;
    }
    
    public void setBatoiLogicProduct(BatoiLogicProduct batoiLogicProduct) {
        this.batoiLogicProduct = batoiLogicProduct;
    }
    public BatoiLogicProvider getBatoiLogicProvider() {
        return this.batoiLogicProvider;
    }
    
    public void setBatoiLogicProvider(BatoiLogicProvider batoiLogicProvider) {
        this.batoiLogicProvider = batoiLogicProvider;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public Date getRequestDate() {
        return this.requestDate;
    }
    
    public void setRequestDate(Date requestDate) {
        this.requestDate = requestDate;
    }
}